<a href="https://colab.research.google.com/github/Svasvil/PracticasBigData/blob/Practica1/SebastianVasquez_SC707_Practica1_JN_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 01  (5%)
## Entregar antes de lección 04, 17:30 horas
**La tarea debe entregarse con las celdas de código ejecutadas, pueden tener "warnings", errores de lógica, pero no errores de sintáxis**

## Creación de variables y vectorización

1. Resuelva la práctica de la presentación (Unidad 2.1) usando una lista con los valores en segundos, transfórmela en un array de numpy, escriba una función que reciba el array y retorne otro con los valores transformados en horas

In [ ]:
## Código de la solución
import numpy as np
Segundos = np.array([3600,7200,1800,4500,10000])
print("Las duraciones son ",Segundos)
Horas = Segundos/3600
print("Las duraciones son ",Horas)


Las duraciones son  [ 3600  7200  1800  4500 10000]
Las duraciones son  [1.         2.         0.5        1.25       2.77777778]


2. Resuelva el ejercicio de la presentación mediante un dataFrame. Cree un dataFrame con una fila y 5 columnas con los valores en segundos. Use apply() para generar una segunda fila con los valores transformados en horas.

In [ ]:
import pandas as pd
import numpy as np
Segundos = np.array([3600,7200,1800,4500,10000]).reshape(1, -1) # el reshape para lo que nos funciona es precisamente para decirle a numpy que si o si el array es de 1x5

Horas = pd.DataFrame(Segundos, index=['Segundos']) #esto lo q hace es que le pone "segundos " de nombre a la linea con los datos
def seg_horas (segundos):
    return segundos / 3600
horas2 = Horas.apply(seg_horas)
print(horas2)

Horas.loc['Horas'] = Horas.iloc[0] # esto lo que hace es vamos a tomar los datos de la posicion 0 del array
#de tabla pasada que hicimos en este caso 'segundos'
print(Horas)


            0    1    2     3         4
Segundos  1.0  2.0  0.5  1.25  2.777778
             0     1     2     3      4
Segundos  3600  7200  1800  4500  10000
Horas     3600  7200  1800  4500  10000


3. Complete el siguiente código para obtener la suma de los valores de cada columna y cada fila, guarde los valores en dos variables distintas

In [ ]:
## Código de la solución
import numpy as np

# Crear una matriz aleatoria 3x3
matrizAleatoria = np.random.randint(1, 10, (3, 3))
print(matrizAleatoria)

suma_columnas = matrizAleatoria.sum(axis=0)
print("sum columna",suma_columnas)
suma_filas = matrizAleatoria.sum(axis=1)
print("sum filas ",suma_filas)

[[8 2 1]
 [1 7 9]
 [8 5 3]]
sum columna [17 14 13]
sum filas  [11 17 16]


4. Complete el siguiente código para convertir los datos en un dataFrame y obtener otro con los registros de los estudiantes que pasaron el curso (nota superior a 70)

In [ ]:
## Código de la solución
import pandas as pd

# Datos iniciales
datos = {'Estudiante': ['Grettel', 'Paula', 'Walter', 'Vinicio'], 'Nota': [85, 60, 58, 92]}
print(datos)

df_notas = pd.DataFrame(datos)
print(df_notas)

estudiantes_aprobados = df_notas[df_notas['Nota'] > 70]
print(" \n estudiantes aprobados \n")
print(estudiantes_aprobados)

{'Estudiante': ['Grettel', 'Paula', 'Walter', 'Vinicio'], 'Nota': [85, 60, 58, 92]}
  Estudiante  Nota
0    Grettel    85
1      Paula    60
2     Walter    58
3    Vinicio    92
 
 estudiantes aprobados 

  Estudiante  Nota
0    Grettel    85
3    Vinicio    92


5. Cargue el archivo personas.csv en un dataFrame y genere un histograma que muestre la cantidad de personas por provincia

In [ ]:
## Código de la solución